### ISSUE TITLE
key not in region use java sdk

### ISSUE THREAD

**Issue by yinghonghui** [tikv/client-java#101]
I use java client sdk to set value in tikv.but pd response Incorrect region info to a key.so report “key not in region” exception when executing set operation.

**Comment by marsishandsome** [comment]
If possible, please provide a code receipt to produce this issue.

**Comment by yinghonghui** [comment]
> If possible, please provide a code receipt to produce this issue.

tikv 3.0  java sdk client 3.0
在压测value 大小10k 
循环插入的1万条数据，get 一万条数据，delete 一万条数据
然后出现了key not in region 的现象。
我的wx ,电话号码15968124041，求指导。

**Comment by yinghonghui** [comment]
> If possible, please provide a code receipt to produce this issue.

tidb集群版本为4.0， tikv java client 3.0报 key not in region 异常，看到这个异常是tidb2.x里已经修复的bug，不知道是什么条件触发了这个异常。 也用golang的客户端 client-go测试过， 并未有这个异常发生。写入的key的特征是前缀一样的key。

现象：
pd返回key相关region 92， 用./pd-ctl check region的一致性，没有异常。日志里看到有region92的分裂和合并。
![image](https://user-images.githubusercontent.com/18246565/100824277-d77a8d00-3490-11eb-9df5-11b77c74cb38.png)
以下是客户端代码：
![image](https://user-images.githubusercontent.com/18246565/100824306-e103f500-3490-11eb-9931-c661d4a01562.png)
服务端的grafana有异常：
![image](https://user-images.githubusercontent.com/18246565/100824326-e8c39980-3490-11eb-9468-867b9507177d.png)
以下是服务端的错误日志
![image](https://user-images.githubusercontent.com/18246565/100824352-f24d0180-3490-11eb-9b5b-c17a79da8655.png)

pd返回region92的startkey比endkey长很多
%E5%9B%BE%E7%89%87
图片.png
847×148 6.07 KB

一致性check没问题
%E5%9B%BE%E7%89%87
图片.png
1072×239 38.5 KB

%E5%9B%BE%E7%89%87
图片.png
1072×75 9.84 KB

**Comment by yinghonghui** [comment]
> If possible, please provide a code receipt to produce this issue.

tidb集群版本为4.0， tikv java client 3.0报 key not in region 异常，看到这个异常是tidb2.x里已经修复的bug，不知道是什么条件触发了这个异常。 也用golang的客户端 client-go测试过， 并未有这个异常发生。写入的key的特征是前缀一样的key。
现象：
pd返回key相关region 92， 用./pd-ctl check region的一致性，没有异常。日志里看到有region92的分裂和合并。
![image](https://user-images.githubusercontent.com/18246565/100824442-21637300-3491-11eb-9496-1d70f1d503ca.png)

以下是客户端代码：
![image](https://user-images.githubusercontent.com/18246565/100824465-288a8100-3491-11eb-922f-a23fb97b9765.png)
服务端的grafana有异常：
![image](https://user-images.githubusercontent.com/18246565/100824483-30e2bc00-3491-11eb-8df4-7d948b2533a3.png)

以下是服务端的错误日志
![image](https://user-images.githubusercontent.com/18246565/100824504-3809ca00-3491-11eb-8ef8-850ea624e4ae.png)
pd返回region92的startkey比endkey长很多

![image](https://user-images.githubusercontent.com/18246565/100824511-3c35e780-3491-11eb-9e0e-62ee6ddad3b7.png)

一致性check没问题
![image](https://user-images.githubusercontent.com/18246565/100824540-4bb53080-3491-11eb-92be-d0a874cda1e2.png)

![image](https://user-images.githubusercontent.com/18246565/100824547-4f48b780-3491-11eb-9083-cfba6652c5e3.png)

**Comment by zekisong** [comment]
我也遇到了同样的问题，看来像tikv自动split时没有encode key，调用findRegionByKey接口会encode key
