### ISSUE TITLE
Latency metrics is different in TiKV grafana & java client

### ISSUE THREAD

**Issue by slow-zhang** [tikv/client-java#130]
Hi there, I use a tikv cluster and java client for testing.

In my test, the java client latency(~100ms) > tikv grafana client latency(tikv detail, grpc ~50ms).  

Could you please help me figure out this problem? Is it a java-client bug, grpc error or java-client error-config?

java client:
```java
public class TiKVOperator {
    private final String pdServers;
    private RawKVClient rawKVClient;

    @PostConstruct
    private void initialize() {
        TiConfiguration conf = TiConfiguration.createRawDefault(pdServers);
        TiSession session = TiSession.getInstance(conf);
        rawKVClient = session.createRawClient();
    }

    public Optional<byte[]> get(String key) {
        ByteString result = rawKVClient.get(ByteString.copyFromUtf8(key));
        if (ByteString.EMPTY.equals(result)) {
            return Optional.empty();
        }
        return Optional.of(result.toByteArray());
    }

    public void set(String key, byte[] value) {
        rawKVClient.put(ByteString.copyFromUtf8(key), ByteString.copyFrom(value));
    }
}
```
```java
Optional<byte[]> newCurrentValue = Metrics.CLIENT.measureTime(
        joining("getlatency"), () -> newTiKVOperator.get(key)
);
```

grpc latency:
![image](https://user-images.githubusercontent.com/24769636/108680631-11f04500-7529-11eb-896d-025e63fe24d2.png)

java client latency
![image](https://user-images.githubusercontent.com/24769636/108680684-22082480-7529-11eb-8205-5d77903c6d96.png)

**Comment by marsishandsome** [comment]
@birdstorm PTAL

**Comment by birdstorm** [comment]
@slow-zhang Hi, thanks for your feedback. Can you please provide the version of TiKV and Java Client?

I will test it for more details.

**Comment by birdstorm** [comment]
Also, is the current test using multiple raw clients? If that is the case, try to

**Comment by slow-zhang** [comment]
> @slow-zhang Hi, thanks for your feedback. Can you please provide the version of TiKV and Java Client?
> 
> I will test it for more details.

        <dependency>
            <groupId>org.tikv</groupId>
            <artifactId>tikv-client-java</artifactId>
            <version>3.0.0</version>
        </dependency>

tikv+pd is deployed by tiup v1.1.2, and tikv version is 4.0.4

**Comment by birdstorm** [comment]
@slow-zhang Hi. Thanks for your feedback, I have located a bug in RegionManager, and here is the fix: 

https://github.com/tikv/client-java/pull/131

You may build from the source, and try it again to see if the problem is resolved.

**Comment by slow-zhang** [comment]
thanks @birdstorm , I have found that the problem is caused by the backoff. thanks anyway
