### ISSUE TITLE
Suggestion for using VisibleForTesting annotation instead of public modification

### ISSUE THREAD

**Issue by honeychen502** [tikv/client-java#21]
Code location in RegionStoreClient
current useage is :
`// TODO: change from public to private
  // because our test needs to implement the
  // preWrite and commit which needs to use
  // lockResolverClient, after implements the
  // write implementation of tispark, we can change
  // it to private
  public final LockResolverClient lockResolverClient`

Only visible for test cases, I think this can be a better choice:
`@VisibleForTesting private final LockResolverClient lockResolverClient;`
use annotion rather than hardcode, maybe more flexible, and less misstake.

**Comment by birdstorm** [comment]
Yep, I will fix it right away.
