### ISSUE TITLE
scan not work

### ISSUE THREAD

**Issue by zekisong** [tikv/client-java#231]
scan(startKey, timestamp) not work
![企业微信截图_04438742-16ff-495b-8cfe-eca819336563](https://user-images.githubusercontent.com/49529656/125069665-9662ef00-e0e9-11eb-9bc4-50395a10b9c6.png)

**Comment by marsishandsome** [comment]
please provide 
- **What did you do**
- **What do you expect**
- **What happens instead**

**Comment by zz-jason** [comment]
I'm going to close this issue, feel free to reopen once you have detailed information about the abnormal behaviors.
