### ISSUE TITLE
Support TLS connections

### ISSUE THREAD

**Issue by kolbe** [tikv/client-java#267]
Please add support for TLS connections to TiKV/PD.

**Comment by kolbe** [comment]
We should support this using a similar mechanism to MySQL Connector/J, that is to say that we should simply rely on the java system property trustStore/keyStore with optional support for a connection-based override.

**Comment by kolbe** [comment]
We should consider that some uses, such as MapReduce-TiDB-Connector (https://github.com/tidb-incubator/TiBigData/blob/master/mapreduce/README.md) maybe require separate TLS contexts for connections to internal cluster APIs and for access to port 4000 on a TiDB server, for example. So we should not assume that someone can use the system default TLS context for all work.

**Comment by ljun0712** [comment]
Currently, after the transmission encryption function between components is enabled in tikv, tikv / client-java cannot be used normally
