### ISSUE TITLE
get unexpected key using scan api

### ISSUE THREAD

**Issue by jjz921024** [tikv/client-java#403]
**Describe the bug**
Invoke the scan api of the txn client with startKey, obtain unexpected data that out of range

for example, there are two key `k|d|0` and `k4|d|0`,  invoke scan with startKey `k4|d|`,
but get unexpected key `k|d|0` additionally.

![企业微信截图_20211207160918](https://user-images.githubusercontent.com/19649281/145984155-8b2cbe26-6b10-45bc-b6b4-ada742633804.png)

**Java Client and TiDB/TiKV version info**
client version: 3.1.2
tikv version:  v4.0.15

**Comment by jjz921024** [comment]
Sorry about reply late.  You are right and i mistake,
What I really want to scan keys that prefixed with `k4|d|`,
Similar to hbase [Prefix filter](https://github.com/apache/hbase/blob/master/hbase-client/src/main/java/org/apache/hadoop/hbase/filter/PrefixFilter.java) feature.
So, do tikv support this feature?

**Comment by jjz921024** [comment]
@zz-jason Sorry about reply late. You are right and i mistake,
What I really want to scan keys that prefixed with k4|d|,
Similar to hbase Prefix filter feature.
So, do tikv support this feature?

**Comment by zz-jason** [comment]
> What I really want to scan keys that prefixed with k4|d|,
> Similar to hbase Prefix filter feature.
> So, do tikv support this feature?

Does the [`scanPrefix()`](https://github.com/tikv/client-java/blob/master/src/main/java/org/tikv/raw/RawKVClientBase.java#L231:L243) satisfy your requirement?

**Comment by jjz921024** [comment]
Yes，But I'm using the txn api instead of raw api.
I don‘t see the corresponding method in the txn api

**Comment by marsishandsome** [comment]
you can find the txn scan api here https://github.com/tikv/client-java/blob/master/src/main/java/org/tikv/txn/KVClient.java#L112

**Comment by zz-jason** [comment]
@jjz921024 I'm going to close this issue, feel free to open it once you have further questions on this topic.
