### ISSUE TITLE
Push SpotBugs results as check run annotations

### ISSUE THREAD

**Issue by iosmanthus** [tikv/client-java#415]
## Feature Request

**Is your feature request related to a problem? Please describe:**

There is no linter tool for client-java now. SpotBugs is a program that uses static analysis to look for bugs in Java code. This tool should be added to our library's Github action. It will help improve the code's quality.

**Describe the feature you'd like:**

Add SpotBugs to Github actions and check each pull request and branch automatically. We may create an issue to track those issues found by SpotBugs.

**Comment by zz-jason** [comment]
1. there are some known issues found in SpotBugs, @iosmanthus @marsishandsome we need to fix them firstly
2. there is a github action for SpotBugs, like this: https://github.com/jwgmeligmeyling/spotbugs-github-action. We need to add the action and triggre it in each PR.
