### ISSUE TITLE
Troubleshoot problems scanned by SpotBugs

### ISSUE THREAD

**Issue by marsishandsome** [tikv/client-java#426]
![middle_img_v2_9e8a6231-a561-431f-b19a-489c66e92b6g](https://user-images.githubusercontent.com/5574887/147054106-832517ee-1028-44dc-95f1-ca6f81270d79.png)

**Comment by zz-jason** [comment]
could you post the original soptbugs reports in the issue description to help us get a deeper understanding of the issues? BTW, it would be better if you can put the instructions about how to generate the report in the issue description.

**Comment by iosmanthus** [comment]
There is a report generated by spotbugs' maven-plugin: https://gist.github.com/iosmanthus/55f861b45f952c4b1393f4dcfba13f77
