### ISSUE TITLE
move irrelevant code out of client-java repo

### ISSUE THREAD

**Issue by zz-jason** [tikv/client-java#519]
## Feature Request

**Is your feature request related to a problem? Please describe:**

client-java is a SDK for interaction between java apps and tikv cluster, just like [client-go](https://github.com/tikv/client-go), [client-rust](https://github.com/tikv/client-rust)

there are some packages that are irrelevant to the target goals, like:

1. org.tikv.cdc: a library to manipulate CDC events
2. org.tikv.br: a library to manipulate BR SST files
3. ...

**Describe the feature you'd like:**

move these irrelevant libraries to a better place, for example, CDC an be can be moved to https://github.com/tikv/migration

**Describe alternatives you've considered:**

N/A

**Teachability, Documentation, Adoption, Migration Strategy:**

N/A

**Comment by zz-jason** [comment]
@birdstorm @marsishandsome PTAL

**Comment by birdstorm** [comment]
Agree. The support for CDC and BR could be moved to an individual library.

**Comment by marsishandsome** [comment]
LGTM
