### ISSUE TITLE
[Ask community] When you plan to release 3.2.0 ?

### ISSUE THREAD

**Issue by leonardBang** [tikv/client-java#525]
Hi, Community.
 
I'm asking this question because the Flink CDC community plan to release its 2.2 version which will support SqlServer and OceanBase, we hope we can support TiDB too, but we depends on the TiKV client 3.2.0, we 're currently using 3.2.0-SNAPSHOT in our [codebase](https://github.com/TiLaker/flink-cdc-connector/blob/main/pom.xml#L74).

**Comment by marsishandsome** [comment]
3.2.0 is planned to be released in next week.

**Comment by leonardBang** [comment]
Thanks for your information @marsishandsome
