### ISSUE TITLE
rawkv: scan return 0 kv pair while exist key ByteString.EMPTY

### ISSUE THREAD

**Issue by iosmanthus** [tikv/client-java#540]
### 1. Describe the bug

`rawScan` interface will return 0 KV-pair while there is an empty key inserted. It could be introduced by the warmup phase of `client-java`.

### 2. Minimal reproduce step (Required)
```java
client.put(ByteString.EMPTY, ByteString.EMPTY);
System.out.println(client.scan(ByteString.EMPTY, 2).size());
```

### 3. What did you see instead (Required)

Output 1

### 4. What did you expect to see? (Required)

Output 0

### 5. What are your Java Client and TiKV versions? (Required)

- Client Java: master
- TiKV: v5.0.3

**Comment by zz-jason** [comment]
an empty value means the key does not exist, am I correct?

**Comment by iosmanthus** [comment]
> an empty value means the key does not exist, am I correct?

Not really, It means inserting a `ByteString.EMPTY` into TiKV.
