### ISSUE TITLE
Display problem with Netty Allocator on grafana 

### ISSUE THREAD

**Issue by marsishandsome** [tikv/client-java#552]
![middle_img_v2_4fdff327-73cb-4977-8b23-2d5a0b9de4fg](https://user-images.githubusercontent.com/5574887/156489817-697cfbbf-1d92-4c36-b680-26735f7c944c.png)

![middle_img_v2_d5499846-2c03-44eb-bd0d-287f59e5317g](https://user-images.githubusercontent.com/5574887/156489828-81c9c1d1-2988-43c2-8bfe-337ef7cf1011.png)

**Comment by zz-jason** [comment]
Sorry, I cannot get your point about the display problem, could you give more explanation on it?

**Comment by marsishandsome** [comment]
> Sorry, I cannot get your point about the display problem, could you give more explanation on it?

<img width="1641" alt="image" src="https://user-images.githubusercontent.com/5574887/156491858-ea14ac94-aedc-4ef0-9df3-a637116972fc.png">
