### ISSUE TITLE
how can i use ttl

### ISSUE THREAD

**Issue by ajian2002** [tikv/client-java#578]
When i run the test i get the error
```
org.tikv.common.exception.KeyException: ttl is not enabled, but get put request with ttl
```
How can I configure the ttl to make the test pass? Is there any relevant information or a clear way to tell me, I need help, thank you

**Comment by iosmanthus** [comment]
TTL feature should enable from TiKV server, with the following config:

```toml
[storage]
enable-ttl = true
```
