### ISSUE TITLE
Reload TLS certificates

### ISSUE THREAD

**Issue by Tema** [tikv/client-java#608]
## Feature Request

**Is your feature request related to a problem?**
Our TLS certificates are rotated on a daily cadence. This breaks TiKV client, which is running for more than a day, as it can't create new connections at this point (when an old connection is closed or there is a change in PD/Storage nodes on the server side).

**Describe the feature you'd like:**
TiKV java client should watch files provided as certs and use them to create new connections if needed. 

**Describe alternatives you've considered:**
The alternative would be watching certs at app level and recreate a full TiKV session and client on a cert change. The downside of that is that it forces to close old client and re-create all connections, which produces additional stress on the server whenever certs are updated.
It could be still reasonable to delegate cert watching to the caller, but at least expose #reloadCert on the TiSession to update internal SSL context of the existing client.

**Comment by iosmanthus** [comment]
There is a TLS reloading feature in master now, more docs are on the way.

You can set an interval to poll the change of TLS context change.
https://github.com/tikv/client-java/blob/aacbb8c849a7c49415cf6a0c0a7f9969583539ff/src/main/java/org/tikv/common/TiConfiguration.java#L1021 

Besides, there is an option for connection recycling that force the old connection to close after a while.

https://github.com/tikv/client-java/blob/aacbb8c849a7c49415cf6a0c0a7f9969583539ff/src/main/java/org/tikv/common/TiConfiguration.java#L702

**Comment by Tema** [comment]
Cool. I can see it in the latest master. The latest 3.2 release which seems dated to last year is missing it, though. When do you plan to do the next release?

Inspecting the code, I found that TiKV client closes old connection on cert change:
https://github.com/tikv/client-java/blob/9ce52d34017e2caaba1a74335e454a87ebeed2af/src/main/java/org/tikv/common/util/ChannelFactory.java#L266-L279

Why does it to do it? Already established connections work just fine with expired certs. I believe they can even reconnect thanks to TLS session resumption. We plan to have pretty large client fleet with often rotated certs and would prefer to avoid  unnecessary reconnects. I believe TiKV server node doesn't touch already established connections on cert change, but just use new cert for new connections.

**Comment by iosmanthus** [comment]
It's an option to force the "insecure" channels to be reused, but the code, for now, has some issues, it should have a zero value to indicate that the connection should not be recycled. Release 3.3 will publish this feature.

**Comment by sunxiaoguang** [comment]
> Cool. I can see it in the latest master. The latest 3.2 release which seems dated to last year is missing it, though. When do you plan to do the next release?
> 
> Inspecting the code, I found that TiKV client closes old connection on cert change:
> 
> https://github.com/tikv/client-java/blob/9ce52d34017e2caaba1a74335e454a87ebeed2af/src/main/java/org/tikv/common/util/ChannelFactory.java#L266-L279
> 
> Why does it to do it? Already established connections work just fine with expired certs. I believe they can even reconnect thanks to TLS session resumption. We plan to have pretty large client fleet with often rotated certs and would prefer to avoid unnecessary reconnects. I believe TiKV server node doesn't touch already established connections on cert change, but just use new cert for new connections.

Do we have a way to update ssl context of an existing ManagedChannel? Without updating ssl context, it probably won't be able to establish new connection for whatever reason after old keys expires.

**Comment by iosmanthus** [comment]
@Tema FYI. client-java 3.3.0 is released in maven central repo: https://mvnrepository.com/artifact/org.tikv/tikv-client-java/3.3.0

**Comment by Tema** [comment]
Thanks for releasing 3.3.0! 

> Do we have a way to update ssl context of an existing ManagedChannel? 
Looks like there is no good way to do it :(

> Without updating ssl context, it probably won't be able to establish new connection for whatever reason after old keys expires.
I believe it will be able to reconnect if TLS Session resumption works as expected even with expired certificates.

Anyway looks like I can avoid connection close by providing very large value `connRecycleTime`. I don't have much concern about leaking channel as our client fleet is deployed pretty regulary.

Thanks for the help!
