### ISSUE TITLE
access column family

### ISSUE THREAD

**Issue by jaguarx** [tikv/client-java#61]
Hi,
  ColumnFamily is carried in RawGet/Put request, but not exposed through RegionStoreClient.
  Wil this become available for use?
  Are there some rules on column family usage?

Best!
Jaguar

**Comment by birdstorm** [comment]
The column family should not be exposed to raw Client APIs for now. Accessing the lock/raft cf is pretty dangerous because it may change the behavior of other clients.

**Comment by zz-jason** [comment]
Java Client is expected to only expose the key-value access APIs to the users. I'm going to close this issue. Feel free to reopen this issue if necessary in the future.
