### ISSUE TITLE
client-java 有开发规划么？

### ISSUE THREAD

**Issue by shichaoyuan** [tikv/client-java#71]
hello

我们公司想基于 tikv 开发一个内部使用的存储产品，但是我们的技术栈主要是 java，看到 client-java 还处于构建阶段，所以想咨询一下 client-java  的开发规划？

我们也希望能将自己的工作贡献给社区。

**Comment by marsishandsome** [comment]
你好

目前client-java项目已经可以用了，但是功能还不太完善，目前我们人手比较有限，计划明年投入人手开始完善，如果贵司有兴趣开发的话，也非常欢迎提PR。
