### ISSUE TITLE
[Postpone] Improve BatchPut API

### ISSUE THREAD

**Issue by birdstorm** [tikv/client-java#79]
增加原子性，或让调用方感知多少条成功多少条失败的（在结果集中体现）(Under discussion)

**Comment by birdstorm** [comment]
Should be done in server side if necessary, and its necessity is still under discussion.

**Comment by zz-jason** [comment]
I'm going to close this issue. If once there is any user request for this feature, we can reopen the issue and discuss the specs and design details at that time.
