### ISSUE TITLE
Gradle build error on mac os.

### ISSUE THREAD

**Issue by mikechengwei** [tikv/client-java#85]
Error log:

```
Execution failed for task ':generateProto'. > protoc: stdout: 
. stderr: /Users/beihaobo/Desktop/client-java/src/main/proto: warning: directory does not exist.   
google/api/annotations.proto: File not found.   configpb.proto: Import "google/api/annotations.proto" was not found or had errors
```

**Comment by mikechengwei** [comment]
@birdstorm

**Comment by birdstorm** [comment]
thanks for reporting, java client is now under reforming, there might be a short period that master cannot be compiled.

We will handle this after the reforming has completed, you may track this project https://github.com/pingcap/tispark/projects/5 for progress. Before then, please use commit 9a0b8681dbbf0c9b372bc6339128232d8fc32f0d instead.

**Comment by mikechengwei** [comment]
@birdstorm 
```
		<dependency>
			<groupId>org.tikv</groupId>
			<artifactId>tikv-client-java</artifactId>
			<version>2.0</version>
		</dependency>
```
How can i get source code for above version?

**Comment by mikechengwei** [comment]
9a0b868 is also have this error log. @birdstorm

**Comment by birdstorm** [comment]
The gradle build is no longer supported since v3.0.0.
