### ISSUE TITLE
建议加入Maven中央仓库，或者Github Maven仓库也可以，或者能在Windows上本地安装成功也可以

### ISSUE THREAD

**Issue by jthinking** [tikv/client-java#95]

**Comment by birdstorm** [comment]
Hi, @jthinking 感谢你的提问。

目前 Maven 中央仓库发布还有一些问题需要处理，成功发布时会在这个 issue 中更新状态。

Windows 中暂时不能支持本地安装，如果有需求或者有兴趣的话欢迎一起帮忙改进~

**Comment by birdstorm** [comment]
Maven versions are released.
